# Fixtures file hold the dependencies for spec helper
fixtures:
  forge_modules:
    # Required
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"    
    yamlfile:
      repo: "reidmv/yamlfile"
      ref: "0.2.0" 
    # Optional
    logrotate:
      repo: "yo61/logrotate"
      ref: "1.3.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.8.0"
    # CentOS only
      # ???         
    # Only for testing (or Puppetfile) - dependencies of above modules
    filemapper:
      repo: "adrien/filemapper"
      ref: "1.1.3"      
  symlinks:
    flapjack: "#{source_dir}"