# Fixtures file hold the dependencies for spec helper
fixtures:
  forge_modules:
    filemapper:
      repo: "adrien/filemapper"
      ref: "1.1.3"    
    apt:
      repo: "puppetlabs/apt"
      ref: "1.8.0"      
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"  
    yamlfile:
      repo: "reidmv/yamlfile"
      ref: "0.2.0"
  symlinks:
    flapjack: "#{source_dir}"