language: ruby
rvm:
- 1.9.3
- 2.1.8
- 2.2.4
env:
- PUPPET_VERSION=4.2.3
- PUPPET_VERSION=4.8.1
bundler_args: --without integration_test development
install:
- bundle install
script:
- bundle exec rake test
#matrix:
#  exclude:
notifications:
  email:
    recipients:
    - nicolas@truyens.com
